name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build & push backend image
      - name: Build & push backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: tsaigopal/budget-planner-backend:latest

      # 5. Build & push frontend image
      - name: Build & push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: tsaigopal/budget-planner-frontend:latest

      # 6. Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update and install Docker / Docker Compose if missing
            if ! command -v docker &> /dev/null; then
              echo "Docker not found, installing..."
              sudo apt-get update
              sudo apt-get install -y docker.io
            fi

            if ! command -v docker-compose &> /dev/null; then
              echo "docker-compose not found, installing..."
              sudo apt-get update
              sudo apt-get install -y python3-pip
              sudo pip3 install docker-compose
            fi

            # Ensure project directory exists
            if [ ! -d "~/budget_planner" ]; then
              git clone https://github.com/2300030889-THOTANAGASAIGOPAL/budget_planner.git ~/budget_planner
            fi

            cd ~/budget_planner

            # Pull latest changes
            git pull origin main || true

            # Deploy with docker-compose
            docker-compose pull
            docker-compose up -d
